### ISSUE TITLE
bank: user registration

### ISSUE THREAD

**Issue by gadjevb** [clouway-incubator/servlets#58]
We should implement the functionality for registering a new user in the system.

To register a user we need to provide unique username and password.

Task required:
- [x] save user in the DB
- [x] create account
- [x] serve raw html page

**Comment by freekman** [comment]
Here is an example for the register issue 

![screenshot from 2016-10-13 09 31 34](https://cloud.githubusercontent.com/assets/8199446/19338783/e516a202-9127-11e6-8018-781ac97a91d8.png)
