### ISSUE TITLE
Deciding not to register

### ISSUE THREAD

**Issue by gadjevb** [clouway-incubator/servlets#60]
As a user I may decide that I don't want to register just now, maybe later.

Scenario: Deciding not to register

Given that Joe has entered the register page.
Given that Joe has decided not to register.
When Joe click on the Cancel button.
Then he sees the main page of the website bank.

**Comment by freekman** [comment]
i think this issue i not needed

**Comment by gadjevb** [comment]
This issue will be closed and combined with **bank: user registration** because it's meaningless to make such little implementations.
