### ISSUE TITLE
bank: jetty server is not starting properly

### ISSUE THREAD

**Issue by mgenov** [clouway-incubator/servlets#94]
It looks like that there is a messy configuration in the JettyServer in Milev's Bank. 

The server starts with: 
```java
    context.setResourceBase(".");
    context.setDescriptor("src/main/webapp/WEB-INF/web.xml");
    context.setResourceBase("../test-jetty-webapp/src/main/webapp");
    context.setContextPath("/");
```

And this test-jetty-webapp folder looks strange. 

This is a pointer to the place in the source: 
https://github.com/clouway-incubator/servlets/blob/milev_bank/src/main/java/com/clouway/http/server/JettyServer.java#L23

**Comment by mgenov** [comment]
cc @freekman

**Comment by freekman** [comment]
i also think this  context.setResourceBase("../test-jetty-webapp/src/main/
webapp"); can be removed what do you suggest for me to sort the problem
with Milev or what

**Comment by mgenov** [comment]
He should have enough information to address it himself I suppose. javadoc should have enough information about this method.

**Comment by martinmilev** [comment]
Both work, but `context.setResourceBase(".")` is returning the directory structure of the project with all the files in it. So you can browse the project from the browser at "localhost:8080".
The correct  configuration would be `context.setResourceBase("../test-jetty-webapp/src/main/webapp")`. It shows only the html and does not return files.
I don't know why the first one is there. I guess it is just old code. Will remove it, but do I need to do PR for it?

**Comment by mgenov** [comment]
PR should be issued and for small changes. They are reviewed even faster then the traditional ones.
